export const AWS = 'aws'
export const GCP = 'gcp'
export const KUBERNETES = 'kubernetes'
export const AZURE = 'azure'

export const CLOUD_LABEL_AWS = 'AWS'
export const CLOUD_LABEL_GCP = 'GCP'
export const CLOUD_LABEL_KUBERNETES = 'Kubernetes'
export const CLOUD_LABEL_AZURE = 'Azure'

export const CLOUD_ARTIFACT_TYPE_AWS = 'massdriver/aws-iam-role'
export const CLOUD_ARTIFACT_TYPE_GCP = 'massdriver/gcp-service-account'
export const CLOUD_ARTIFACT_TYPE_KUBERNETES = 'massdriver/kubernetes-cluster'
export const CLOUD_ARTIFACT_TYPE_AZURE = 'massdriver/azure-service-principal'

export const CLOUD_CREDENTIAL_LABEL_AWS = 'AWS IAM Role'
export const CLOUD_CREDENTIAL_LABEL_GCP = 'GCP Service Account'
export const CLOUD_CREDENTIAL_LABEL_KUBERNETES = 'Kubernetes Cluster'
export const CLOUD_CREDENTIAL_LABEL_AZURE = 'Azure Service Principal'

export const CLOUD_ICON_AWS = 'assets/clouds/aws-icon.png'
export const CLOUD_ICON_GCP = 'assets/clouds/gcp-icon.png'
export const CLOUD_ICON_AZURE = 'assets/clouds/azure-icon.png'
export const CLOUD_ICON_KUBERNETES = 'assets/clouds/kubernetes-icon.png'

export const CLOUD_LOGO_AWS = 'assets/clouds/aws-logo.png'
export const CLOUD_LOGO_GCP = 'assets/clouds/gcp-logo.png'
export const CLOUD_LOGO_KUBERNETES = 'assets/clouds/kubernetes-logo.png'
export const CLOUD_LOGO_AZURE = 'assets/clouds/azure-logo.png'

export const CLOUD_LABELS = {
  [AWS]: CLOUD_LABEL_AWS,
  [GCP]: CLOUD_LABEL_GCP,
  [KUBERNETES]: CLOUD_LABEL_KUBERNETES,
  [AZURE]: CLOUD_LABEL_AZURE,
  [CLOUD_ARTIFACT_TYPE_AWS]: CLOUD_LABEL_AWS,
  [CLOUD_ARTIFACT_TYPE_GCP]: CLOUD_LABEL_GCP,
  [CLOUD_ARTIFACT_TYPE_KUBERNETES]: CLOUD_LABEL_KUBERNETES,
  [CLOUD_ARTIFACT_TYPE_AZURE]: CLOUD_LABEL_AZURE
}

export const CLOUD_CREDENTIAL_LABELS = {
  [AWS]: CLOUD_CREDENTIAL_LABEL_AWS,
  [GCP]: CLOUD_CREDENTIAL_LABEL_GCP,
  [KUBERNETES]: CLOUD_CREDENTIAL_LABEL_KUBERNETES,
  [AZURE]: CLOUD_CREDENTIAL_LABEL_AZURE,
  [CLOUD_ARTIFACT_TYPE_AWS]: CLOUD_CREDENTIAL_LABEL_AWS,
  [CLOUD_ARTIFACT_TYPE_GCP]: CLOUD_CREDENTIAL_LABEL_GCP,
  [CLOUD_ARTIFACT_TYPE_KUBERNETES]: CLOUD_CREDENTIAL_LABEL_KUBERNETES,
  [CLOUD_ARTIFACT_TYPE_AZURE]: CLOUD_CREDENTIAL_LABEL_AZURE
}

export const CLOUD_ARTIFACT_TYPES = {
  [AWS]: CLOUD_ARTIFACT_TYPE_AWS,
  [GCP]: CLOUD_ARTIFACT_TYPE_GCP,
  [KUBERNETES]: CLOUD_ARTIFACT_TYPE_KUBERNETES,
  [AZURE]: CLOUD_ARTIFACT_TYPE_AZURE
}

export const CLOUD_ICONS = {
  [AWS]: CLOUD_ICON_AWS,
  [GCP]: CLOUD_ICON_GCP,
  [AZURE]: CLOUD_ICON_AZURE,
  [KUBERNETES]: CLOUD_ICON_KUBERNETES,
  [CLOUD_ARTIFACT_TYPE_AWS]: CLOUD_ICON_AWS,
  [CLOUD_ARTIFACT_TYPE_GCP]: CLOUD_ICON_GCP,
  [CLOUD_ARTIFACT_TYPE_AZURE]: CLOUD_ICON_AZURE,
  [CLOUD_ARTIFACT_TYPE_KUBERNETES]: CLOUD_ICON_KUBERNETES
}

export const CLOUD_LOGOS = {
  [AWS]: CLOUD_LOGO_AWS,
  [GCP]: CLOUD_LOGO_GCP,
  [KUBERNETES]: CLOUD_LOGO_KUBERNETES,
  [AZURE]: CLOUD_LOGO_AZURE,
  [CLOUD_ARTIFACT_TYPE_AWS]: CLOUD_LOGO_AWS,
  [CLOUD_ARTIFACT_TYPE_GCP]: CLOUD_LOGO_GCP,
  [CLOUD_ARTIFACT_TYPE_KUBERNETES]: CLOUD_LOGO_KUBERNETES,
  [CLOUD_ARTIFACT_TYPE_AZURE]: CLOUD_LOGO_AZURE
}

export const CLOUD_LOGOS_BY_TYPE_MAP = {
  ECR: CLOUD_LOGO_AWS,
  GAR: CLOUD_LOGO_GCP,
  ACR: CLOUD_LOGO_AZURE
}
