import stylin from '../utils/stylin'

import FormDataSection from './FormDataSection'
import FormSection from './FormSection'
import PanelHeader from './PanelHeader'
import LoadingSpinner from './LoadingSpinner'
import Custom404 from './Custom404'
import Collapse from './Collapse'

import Stack from '@mui/material/Stack'
import Divider from '@mui/material/Divider'
import Box from '@mui/material/Box'
import Typography from '@mui/material/Typography'

const FormView = ({
  loading,
  error,
  schema,
  uiSchema,
  formData,
  formContext,
  onSubmit,
  onChange
}) => (
  <>
    <PanelHeader
      label="Form"
      subLabel="View the configuration form generated by your 'params' and 'ui' objects from your massdriver.yaml. Fill it out and see the form data update live."
    />
    {loading ? (
      <LoadingSpinner />
    ) : error ? (
      <Custom404 small>
        <Typography variant='h3'>
          Bundle Schemas not found
        </Typography>
        <Typography variant='h6'>
          We encountered an issue parsing your bundle schemas. Please restart the dev server and try again.
        </Typography>
      </Custom404>
    ) : (
      <Stack divider={<Divider />}>
        <Collapse
          sx={{ backgroundColor: 'white', px: '50px' }}
          header={(
            <Typography sx={{ fontSize: '26px' }}>
              Form Data
            </Typography>
          )}
        >
          <FormDataSection
            formData={formData}
          />
        </Collapse>
        <Collapse
          sx={{ backgroundColor: 'white', px: '50px' }}
          header={(
            <Typography sx={{ fontSize: '26px' }}>
              Form
            </Typography>
          )}
        >
          <FormSection
            schema={schema}
            uiSchema={uiSchema}
            formData={formData}
            formContext={formContext}
            onSubmit={onSubmit}
            onChange={onChange}
          />
        </Collapse>
      </Stack>
    )}
  </>
)

export default FormView

const Container = stylin(Box)({
  px: '120px',
  py: '20px',
})
