import stylin from '../utils/stylin'

import FormDataSection from './FormDataSection'
import ConfigureForm from './OldConfigureForm/ConfigureForm.container'
import PanelHeader from './PanelHeader'
import LoadingSpinner from './LoadingSpinner'
import Custom404 from './Custom404'
import Collapse from './Collapse'

import Stack from '@mui/material/Stack'
import Divider from '@mui/material/Divider'
import Box from '@mui/material/Box'
import Typography from '@mui/material/Typography'

const FormView = ({
  loading,
  error,
  schema,
  uiSchema,
  formData,
  formContext,
  setFormData,
  onSubmit,
  onChange
}) => (
  <>
    <PanelHeader
      label="Form Validator"
      subLabel="View the configuration form generated by your 'params' and 'ui' objects from your massdriver.yaml. Fill it out and see the form data update live. Click 'Validate' to validate form data against your 'params' schema."
    />
    {loading ? (
      <LoadingSpinner />
    ) : error ? (
      <Custom404 small>
        <Typography variant='h3'>
          Bundle Schemas not found
        </Typography>
        <Typography variant='h6'>
          We encountered an issue parsing your bundle schemas. Please restart the dev server and try again.
        </Typography>
      </Custom404>
    ) : schema && uiSchema && (
      <Stack divider={<Divider />}>
        <Collapse
          sx={{ backgroundColor: 'white', px: '50px' }}
          header={(
            <Typography sx={{ fontSize: '26px' }}>
              Form
            </Typography>
          )}
        >
          <ConfigureForm
            schema={schema}
            uiSchema={uiSchema}
            formData={formData}
            formContext={formContext}
            onSubmit={onSubmit}
            onChange={onChange}
            setFormData={setFormData}
          />
        </Collapse>
        <Collapse
          sx={{ backgroundColor: 'white', px: '50px' }}
          header={(
            <Typography sx={{ fontSize: '26px' }}>
              Form Data
            </Typography>
          )}
        >
          <FormDataSection
            formData={formData}
          />
        </Collapse>
      </Stack>
    )}
  </>
)

export default FormView

const Container = stylin(Box)({
  px: '120px',
  py: '20px',
})
