import stylin from 'utils/stylin'

import Section from 'components/Section'
import ConfigPanel from 'components/ConfigPanel/ConfigPanel'

import Box from '@mui/material/Box'
import Typography from '@mui/material/Typography'
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button'

const SECTION_TITLE = "Bundle configuration form validator"

const FormSection = ({
  loading,
  error,
  // Form stuff
  formContext = {},
  schema,
  uiSchema,
  formData = {},
  onFormDataChange,
  submitForm,
  // Options menu stuff
  selectedPreset,
  isExpandedView,
  presetOptions,
  onConfigOptionClick,
  shouldShowPresets = true,
  hasStaleParams
}) => (
  <Section
    title={SECTION_TITLE}
    description={<>The configuration form that is generated by the <strong>params</strong> in the <strong>massdriver.yaml</strong>. Use this tool to validate the form and ensure it is generated properly.</>}
  >
    <Container>
      {
        loading ? (
          <EmptyMessage>Loading...</EmptyMessage>
        ) : error ? (
          <EmptyMessage>Error: There was an issue parsing your bundle params.</EmptyMessage>
        ) :
          <Stack
            direction={{
              md: 'column',
              lg: 'row'
            }}
          >
            <ConfigPanel
              // Form stuff
              formContext={formContext}
              schema={schema}
              uiSchema={uiSchema}
              formData={formData}
              onFormDataChange={onFormDataChange}
              submitForm={submitForm}
              // Options menu stuff
              selectedPreset={selectedPreset}
              isExpandedView={isExpandedView}
              presetOptions={presetOptions}
              onConfigOptionClick={onConfigOptionClick}
              shouldShowPresets={shouldShowPresets}
              hasStaleParams={hasStaleParams}
            >
              <Button
                type="submit"
              >
                Validate
              </Button>
            </ConfigPanel>
          </Stack>
      }
    </Container>
  </Section>
)

export default FormSection

const Container = stylin(Box)({
  display: 'flex',
  flexDirection: 'column',
  gap: '10px',
  p: '12px'
})

const EmptyMessage = stylin(Typography)(({ theme }) => ({
  fontSize: '10px',
  color: theme.palette.grey[900],
  fontWeight: 'bold',
}))
